#!/usr/bin/env bash
################################################################################
#         ____  ___________               __          __                       #
#        / __ \/ __/ __/ (_)___  ___     / /   ____ _/ /_                      #
#       / / / / /_/ /_/ / / __ \/ _ \   / /   / __ `/ __ \                     #
#      / /_/ / __/ __/ / / / / /  __/  / /___/ /_/ / /_/ /                     #
#      \____/_/ /_/ /_/_/_/ /_/\___/  /_____/\__,_/_.___/                      #
#                                                                              #
#      Copyright (C) 2025-2026 Offline Lab                                     #
#      Contact: info@offline-lab.com                                           #
#      SPDX-License-Identifier: AGPL-3.0-only                                  #
################################################################################
# vi: ft=bash
# shellcheck shell=bash disable=SC1091,SC2312
set -euo pipefail

source framework || exit 1
import zram

function zram_swap::main() {
    log::trace "${FUNCNAME[0]}: managing zram swap"

    depends::is_root || exit::error "${FUNCNAME[0]}: must be run as root"

    # Load site config if present (overrides ZRAM_* env vars)
    if [[ -f /etc/default/zram-swap ]]; then
        # shellcheck source=/dev/null
        source /etc/default/zram-swap
    fi

    local cmd="${1:-}"
    case "${cmd}" in
        init | start) zram::start ;;
        end | stop) zram::stop ;;
        *) exit::error "${FUNCNAME[0]}: usage: $(basename "${0}") (start|stop)" ;;
    esac
}

zram_swap::main "${@}"
