################################################################################
#         ____  ___________               __          __                       #
#        / __ \/ __/ __/ (_)___  ___     / /   ____ _/ /_                      #
#       / / / / /_/ /_/ / / __ \/ _ \   / /   / __ `/ __ \                     #
#      / /_/ / __/ __/ / / / / /  __/  / /___/ /_/ / /_/ /                     #
#      \____/_/ /_/ /_/_/_/ /_/\___/  /_____/\__,_/_.___/                      #
#                                                                              #
#      Copyright (C) 2025-2026 Offline Lab                                     #
#      Contact: info@offline-lab.com                                           #
#                                                                              #
#      SPDX-License-Identifier: GPL-2.0-only                                   #
#                                                                              #
################################################################################
---

{{- $architecture := .architecture }}

architecture: {{ $architecture }}

actions:
- action: run
  description: "Reconfigure rfkill settings for bluetooth"
  chroot: false
  command: |
    # Newer versions of raspberrypi-sys-mods set rfkill.default_state=0 to prevent
    # radiating on 5GHz bands until the WLAN regulatory domain is set.
    # Unfortunately, this also blocks bluetooth, so we whitelist the known
    # on-board BT adapters here.
    mkdir -p "$ROOTDIR"/var/lib/systemd/rfkill/;

    #           5                 miniuart 4      miniuart Zero   miniuart other  other
    for addr in 107d50c000.serial 3f215040.serial 20215040.serial fe215040.serial soc; do
        echo 0 >"$ROOTDIR"/var/lib/systemd/rfkill/platform-${addr}:bluetooth
    done
