#!/usr/bin/env bash
################################################################################
#         ____  ___________               __          __                       #
#        / __ \/ __/ __/ (_)___  ___     / /   ____ _/ /_                      #
#       / / / / /_/ /_/ / / __ \/ _ \   / /   / __ `/ __ \                     #
#      / /_/ / __/ __/ / / / / /  __/  / /___/ /_/ / /_/ /                     #
#      \____/_/ /_/ /_/_/_/ /_/\___/  /_____/\__,_/_.___/                      #
#                                                                              #
#      Copyright (C) 2025-2026 Offline Lab                                     #
#      Contact: info@offline-lab.com                                           #
#      SPDX-License-Identifier: AGPL-3.0-only                                  #
################################################################################
# vi: ft=bash
# shellcheck shell=bash disable=SC1091,SC2312
set -euo pipefail

source framework || exit 1

readonly BOOT_CONFIG="/boot/firmware/config/disco.yaml"
readonly DATA_CONFIG="/data/config/disco/config.yaml"
readonly DEFAULT_CONFIG="/etc/disco/config.yaml"

function provision_disco::main() {
    log::trace "${FUNCNAME[0]}: provisioning disco config"

    fs::ensure_dir "${DATA_CONFIG}"

    fs::is_file "${DATA_CONFIG}" && return 0

    if fs::is_file "${BOOT_CONFIG}"; then
        cp "${BOOT_CONFIG}" "${DATA_CONFIG}"
        log::info "${FUNCNAME[0]}: provisioned from ${BOOT_CONFIG}"
    elif fs::is_file "${DEFAULT_CONFIG}"; then
        cp "${DEFAULT_CONFIG}" "${DATA_CONFIG}"
        log::info "${FUNCNAME[0]}: provisioned from defaults"
    fi

    chmod 644 "${DATA_CONFIG}" 2>/dev/null || true
}

provision_disco::main "${@}"
