################################################################################
#         ____  ___________               __          __                       #
#        / __ \/ __/ __/ (_)___  ___     / /   ____ _/ /_                      #
#       / / / / /_/ /_/ / / __ \/ _ \   / /   / __ `/ __ \                     #
#      / /_/ / __/ __/ / / / / /  __/  / /___/ /_/ / /_/ /                     #
#      \____/_/ /_/ /_/_/_/ /_/\___/  /_____/\__,_/_.___/                      #
#                                                                              #
#      Copyright (C) 2025-2026 Offline Lab                                     #
#      Contact: info@offline-lab.com                                           #
#      SPDX-License-Identifier: AGPL-3.0-only                                  #
################################################################################

[system]
compatible=offlinelab-pi-zero-2w
bootloader=uboot
mountprefix=/run/rauc
statusfile=/data/config/rauc.status

[keyring]
path=/etc/rauc/keyring.pem

[slot.kernel.0]
device=/dev/mmcblk0p5
type=raw
bootname=A

[slot.rootfs.0]
device=/dev/mmcblk0p6
type=raw
parent=kernel.0

[slot.kernel.1]
device=/dev/mmcblk0p7
type=raw
bootname=B

[slot.rootfs.1]
device=/dev/mmcblk0p8
type=raw
parent=kernel.1
