[system]
compatible=offlinelab-pi-zero-2w
bootloader=uboot
mountprefix=/run/rauc
statusfile=/data/config/rauc.status

[keyring]
path=/etc/rauc/keyring.pem

[slot.kernel.0]
device=/dev/mmcblk0p5
type=raw
bootname=A

[slot.rootfs.0]
device=/dev/mmcblk0p6
type=raw
parent=kernel.0

[slot.kernel.1]
device=/dev/mmcblk0p7
type=raw
bootname=B

[slot.rootfs.1]
device=/dev/mmcblk0p8
type=raw
parent=kernel.1
