Port 22
AddressFamily any
ListenAddress 0.0.0.0
UsePAM no

PasswordAuthentication no
ChallengeResponseAuthentication no
HostbasedAuthentication no
KbdInteractiveAuthentication no

IgnoreUserKnownHosts yes
PubkeyAuthentication yes

PermitRootLogin prohibit-password
PermitEmptyPasswords no

SyslogFacility AUTH
LogLevel INFO

LoginGraceTime 30
StrictModes yes
MaxAuthTries 2
MaxSessions 10

ClientAliveInterval 300
ClientAliveCountMax 2

AllowUsers root admin
AllowGroups sshusers
