#!/usr/bin/env bash
################################################################################
#         ____  ___________               __          __                       #
#        / __ \/ __/ __/ (_)___  ___     / /   ____ _/ /_                      #
#       / / / / /_/ /_/ / / __ \/ _ \   / /   / __ `/ __ \                     #
#      / /_/ / __/ __/ / / / / /  __/  / /___/ /_/ / /_/ /                     #
#      \____/_/ /_/ /_/_/_/ /_/\___/  /_____/\__,_/_.___/                      #
#                                                                              #
#      Copyright (C) 2025-2026 Offline Lab                                     #
#      Contact: info@offline-lab.com                                           #
#      SPDX-License-Identifier: AGPL-3.0-only                                  #
################################################################################
# vi: ft=bash
# shellcheck shell=bash disable=SC1091,SC2312
set -euo pipefail

source framework || exit 1

function show_ip::main() {
    log::trace "${FUNCNAME[0]}: updating IP display"

    local ip
    ip="$(ip -4 addr show wlan0 2>/dev/null | awk '/inet / {print $2; exit}' | cut -d/ -f1)"

    if [[ -z "${ip}" ]]; then
        log::info "${FUNCNAME[0]}: no IPv4 address on wlan0"
        return 0
    fi

    if [[ -e /tmp/.psplash ]]; then
        psplash-write "MSG WiFi: ${ip}" 2>/dev/null || true
    fi

    log::info "${FUNCNAME[0]}: ${ip}"
}

show_ip::main "${@}"
